#ifndef CONNECTORPLUGIN_GLOBAL_H
#define CONNECTORPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONNECTORPLUGIN_LIBRARY)
#  define CONNECTORPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONNECTORPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONNECTORPLUGIN_GLOBAL_H
