#ifndef LUNAPLUGIN_GLOBAL_H
#define LUNAPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LUNAPLUGIN_LIBRARY)
#  define LUNAPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LUNAPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LUNAPLUGIN_GLOBAL_H
